### PR TITLE
Fix user agent for text app

### LINKED ISSUE #1967: Fix the user-agent for online editing
### Steps to reproduce
1. Create blank Xcode project with a single `WKWebView`
2. Set the `WKWebView`'s`.customUserAgent` to *Mozilla/5.0 (iOS) Nextcloud-iOS/4.4.0*
3. Load a *directEditing* url with that webview
4. Try e.g. passing an image
5. Do the same but adding *AppleWebKit/605.1.15 Mobile/14E304* to the user-agent

### Actual behaviour
When loading without the additional user-agent components pasting images fails. 

### Proposed solution
Change the user-agent at least for `NCViewerNextcloudText`. 
Or if it's needed for other competent of the web app change the user-agent in general. ~~However, this would also require changes in the server.~~

### Reasoning or why should it be changed/implemented?
Some 3rd party libraries and frameworks use the user-agent for platform specific workarounds.
This might be also be the root cause for other issues and glitches with office apps using the Nextcloud iOS app.
Would probably also be a good idea to check the Android app for similar issues @tobiasKaminsky @juliushaertl 

E.g. 3rd party libraries used by nextcloud/text:
https://github.com/ProseMirror/prosemirror-view/blob/d8c4bb1c238d814359a345e576fdfcaaa17aabd2/src/browser.js
https://github.com/ueberdosis/tiptap/blob/e07a5b625d90c77fc5820e5eefa093d3cfb96512/packages/core/src/utilities/isiOS.ts

### Logs

JS Text logs using a WKWebView, attempting to paste an image:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) - http://localhost:8080/s/%7Btoken%7D/download?files=blob%3Ahttp%3A%2F%2F[...]
```

### Environment data

**iOS version:** e.g. iOS 15.4

**Nextcloud iOS app version:** `develop` branch

**Nextcloud version:** 24.0.0RC1

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Fix #1967 

- allow pasting images from the pasteboard + preview (NC 24)
- fix keyboard dismisses after *Cut*
- potential fix for:
  - #1631 
  - nextcloud/text#1927

### CODE REVIEW

File: iOSClient/Utility/NCUtility.swift [hunk 1]
```diff
@@ -28,6 +28,7 @@ import NCCommunication
 import PDFKit
 import Accelerate
 import CoreMedia
+import WebKit
```
Comment (marinofaggiana) [inline iOSClient/Utility/NCUtility.swift:31]: Need WebKit ?

**Review by marinofaggiana — CHANGES_REQUESTED** [review]
Read comments.

File: iOSClient/Utility/NCUtility.swift (hunk 1 above)
Comment (thisIsTheFoxe) [reply iOSClient/Utility/NCUtility.swift]: Used for testing. Removed it.

**Review by marinofaggiana — APPROVED** [review]
