### PR TITLE
Fix only 1 file uploading when selecting multiple

### LINKED ISSUE #2532: Upload file -> selecting multiple files -> only 1 file uploads
https://github.com/nextcloud/ios/assets/6960329/233acd2c-747b-40e0-9f35-1fd430a32371

### PR DESCRIPTION
**Pull request by mpivchev**
This closes #2532 

- Fixes multiple files not uploading 
- Also fixes conflict window, where before it would only show 1 conflict and ignore the rest. Now it shows multiple conflicts (if any), and processes all of them, while files that don't have a conflict continue being uploaded normally.

### CODE REVIEW

File: iOSClient/Main/NCPickerViewController.swift [hunk 1]
```diff
@@ -155,13 +153,17 @@ class NCDocumentPickerViewController: NSObject, UIDocumentPickerDelegate {
             NCViewer.shared.view(viewController: viewController, metadata: metadata, metadatas: [metadata], imageIcon: nil)
 
         } else {
+            let serverUrl = appDelegate.activeServerUrl
+
+            var metadatas = [tableMetadata]()
+            var metadatasInConflict = [tableMetadata]()
 
             for urlIn in urls {
+                let ocId = NSUUID().uuidString
```
Comment (mpivchev) [inline iOSClient/Main/NCPickerViewController.swift:162]: We used the same id for all files, which caused them to get overwritten in Realm. This is fixed.

File: iOSClient/Main/NCPickerViewController.swift [hunk 2]
```diff
@@ -172,19 +174,23 @@ class NCDocumentPickerViewController: NSObject, UIDocumentPickerDelegate {
...
+                    conflict.delegate = appDelegate
+                    conflict.serverUrl = serverUrl
+                    conflict.metadatasUploadInConflict = metadatasInConflict
 
-                } else {
-                    NCNetworkingProcessUpload.shared.createProcessUploads(metadatas: [metadataForUpload], completion: { _ in })
+                    appDelegate.window?.rootViewController?.present(conflict, animated: true, completion: nil)
                 }
             }
         }
```
Comment (mpivchev) [inline iOSClient/Main/NCPickerViewController.swift:196]: Files in conflict will go through `NCCreateFormUploadConflict`, while the rest would continue uploading normally.

**Comment by mpivchev** [comment]
@marinofaggiana It would be great if you can test this manually, in case i missed anything. I will also try to make some unit/integration tests for this.

**Comment by mpivchev** [comment]
@marinofaggiana done
